version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map port 80 of the container to port 80 of the host
    environment:
      NODE_ENV: production  # Set the environment to production
