name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment for building the React app
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run unit tests
      - name: Run unit tests
        run: npm test

      # Step 5: Set up Docker and Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 6: Log in to DockerHub using Docker's official GitHub Action
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker image
      - name: Build Docker image
        run: docker build -t linoyk/stock-price-tracker .

      # Step 8: Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push linoyk/stock-price-tracker

      # Step 9: Upload Docker Image Info for Deployment Workflow
      - name: Upload Image Tag for Deployment
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-tag
          path: linoyk/stock-price-tracker
