name: Build, Push, and Deploy Stock-Price-Tracker App

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React App for Production
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/stock-price-tracker:latest .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/stock-price-tracker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies in a virtual environment
        run: |
          sudo apt-add-repository ppa:ansible/ansible -y
          sudo apt-get update
          sudo apt-get install -y ansible python3-venv python3-pip
          python3 -m venv ansible-env
          source ansible-env/bin/activate
          pip install --upgrade pip
          pip install ansible==6.7.0 requests botocore boto boto3
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Run Ansible Playbook to deploy Stock-Price-Tracker
        run: |
          source ansible-env/bin/activate
          ansible-playbook ansible/ansible-deploy.yaml --ssh-common-args='-o StrictHostKeyChecking=no'
        shell: bash
