name: Deploy to AWS with Ansible

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed  # Trigger on completion of the build workflow

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only trigger if the build was successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Docker Image Info for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-tag
          path: linoyk/stock-price-tracker

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible and Boto3
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3

      - name: Install AWS Ansible Collection
        run: |
          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.aws

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ansible-playbook ./ansible/ansible-deploy.yaml -i localhost, -vvv
