name: Build and Push Stock-Price-Tracker Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/stock-price-tracker:latest

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/stock-price-tracker:latest
