name: upload my stock-price-tracker image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/stock-price-tracker:latest

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/stock-price-tracker:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy stock-price-tracker app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop stock-price-tracker || true
            sudo docker rm stock-price-tracker || true
            sudo docker rmi ${{ secrets.DOCKER_USER }}/stock-price-tracker || true
            sudo docker pull ${{ secrets.DOCKER_USER }}/stock-price-tracker
            sudo docker run --name stock-price-tracker -d -p 80:3000 ${{ secrets.DOCKER_USER }}/stock-price-tracker
